config/routes.rb
Rails.application.routes.draw do
  devise_for :residents, controllers: {
                       registrations: 'residents/registrations',
                       :omniauth_callbacks => "residents/omniauth_callbacks"
                   }
  root 'residents#index'

  get '/logout' => 'application#logout'
  resources :families
  resources :complaints
  resources :communities
  resources :people
  resources :neighbourhoods
  resources :polls

  get 'residents/me' => 'residents#me'
  resources :residents do
    get :approve, :on => :collection
  end
  resources :attempts
  resources :surveys
  resources :apartments
  resources :flats
  resources :workers
  resources :tags
  resources :residential_buildings
  resources :living_spaces
  resources :information

  resources :posts do
    resources :comments
  end

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :neighbourhood
  has_many :flats
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :information
  belongs_to :resident
end

app/models/community.rb
class Community < ActiveRecord::Base
  has_and_belongs_to_many :residents
  has_and_belongs_to_many :workers

  has_many :members
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  belongs_to :resident
end

app/models/family.rb
class Family < ActiveRecord::Base
  has_many :residents
  belongs_to :living_space
end

app/models/flat.rb
class Flat < ActiveRecord::Base
  belongs_to :apartment
  has_many :residents
end

app/models/information.rb
class Information < ActiveRecord::Base
  has_many :tags
  has_many :comments
  belongs_to :resident
end

app/models/living_space.rb
class LivingSpace < ActiveRecord::Base
  has_one :family
  belongs_to :neighbourhood
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :resident
  belongs_to :community
end

app/models/neighbourhood.rb
class Neighbourhood < ActiveRecord::Base
  has_many :residents
  has_many :living_spaces
  has_many :apartments
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :resident
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :resident
  has_many :comments
  def score
    self.get_upvotes.size - self.get_downvotes.size
  end
end

__END__

How to implement a blog


There will be a blog controller.


index.html.erb
--------------
Will show a list of all the posts


tag

app/models/resident.rb
class Resident < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :first_name, length: {minimum:2}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:facebook]
  belongs_to :family
  belongs_to :neighbourhood
  belongs_to :living_space
  has_many :posts
  has_and_belongs_to_many :communities
  has_many :comments
  has_many :polls
  has_many :informations
  has_many :members

  has_surveys

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |resident|
      resident.email = auth.info.email
      resident.password = Devise.friendly_token[0,20]
      resident.first_name = auth.info.name   # assuming the user model has a name
      resident.last_name = "."
      print "Image coming here"
      #user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  has_and_belongs_to_many :communities 
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :use_count)
    end
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :use_count %><br>
    <%= f.number_field :use_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Use count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.use_count %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Use count:</strong>
  <%= @tag.use_count %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>