config/routes.rb
Rails.application.routes.draw do
  devise_for :residents, controllers: {
                       registrations: 'residents/registrations',
                       :omniauth_callbacks => "residents/omniauth_callbacks"
                   }
  root 'residents#index'

  get '/logout' => 'application#logout'
  resources :families
  resources :complaints
  resources :communities
  resources :people
  resources :neighbourhoods
  resources :polls

  get 'residents/me' => 'residents#me'
  resources :residents do
    get :approve, :on => :collection
  end
  resources :attempts
  resources :surveys
  resources :apartments
  resources :flats
  resources :workers
  resources :tags
  resources :residential_buildings
  resources :living_spaces
  resources :information

  resources :posts do
    resources :comments
  end

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :neighbourhood
  has_many :flats
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :information
  belongs_to :resident
end

app/models/community.rb
class Community < ActiveRecord::Base
  has_and_belongs_to_many :residents
  has_and_belongs_to_many :workers

  has_many :members
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  belongs_to :resident
end

app/models/family.rb
class Family < ActiveRecord::Base
  has_many :residents
  belongs_to :living_space
end

app/models/flat.rb
class Flat < ActiveRecord::Base
  belongs_to :apartment
  has_many :residents
end

app/models/information.rb
class Information < ActiveRecord::Base
  has_many :tags
  has_many :comments
  belongs_to :resident
end

app/models/living_space.rb
class LivingSpace < ActiveRecord::Base
  has_one :family
  belongs_to :neighbourhood
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :resident
  belongs_to :community
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :resident
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :resident
  has_many :comments
  def score
    self.get_upvotes.size - self.get_downvotes.size
  end
end

__END__

How to implement a blog


There will be a blog controller.


index.html.erb
--------------
Will show a list of all the posts


tag

app/models/resident.rb
class Resident < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :first_name, length: {minimum:2}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:facebook]
  belongs_to :family
  belongs_to :neighbourhood
  belongs_to :living_space
  has_many :posts
  has_and_belongs_to_many :communities
  has_many :comments
  has_many :polls
  has_many :informations
  has_many :members

  has_surveys

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |resident|
      resident.email = auth.info.email
      resident.password = Devise.friendly_token[0,20]
      resident.first_name = auth.info.name   # assuming the user model has a name
      resident.last_name = "."
      print "Image coming here"
      #user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/models/residential_building.rb
class ResidentialBuilding < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  has_and_belongs_to_many :communities 
end

app/controllers/residential_buildings_controller.rb
class ResidentialBuildingsController < ApplicationController
  before_action :set_residential_building, only: [:show, :edit, :update, :destroy]

  # GET /residential_buildings
  # GET /residential_buildings.json
  def index
    @residential_buildings = ResidentialBuilding.all
  end

  # GET /residential_buildings/1
  # GET /residential_buildings/1.json
  def show
  end

  # GET /residential_buildings/new
  def new
    @residential_building = ResidentialBuilding.new
  end

  # GET /residential_buildings/1/edit
  def edit
  end

  # POST /residential_buildings
  # POST /residential_buildings.json
  def create
    @residential_building = ResidentialBuilding.new(residential_building_params)

    respond_to do |format|
      if @residential_building.save
        format.html { redirect_to @residential_building, notice: 'Residential building was successfully created.' }
        format.json { render :show, status: :created, location: @residential_building }
      else
        format.html { render :new }
        format.json { render json: @residential_building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residential_buildings/1
  # PATCH/PUT /residential_buildings/1.json
  def update
    respond_to do |format|
      if @residential_building.update(residential_building_params)
        format.html { redirect_to @residential_building, notice: 'Residential building was successfully updated.' }
        format.json { render :show, status: :ok, location: @residential_building }
      else
        format.html { render :edit }
        format.json { render json: @residential_building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residential_buildings/1
  # DELETE /residential_buildings/1.json
  def destroy
    @residential_building.destroy
    respond_to do |format|
      format.html { redirect_to residential_buildings_url, notice: 'Residential building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residential_building
      @residential_building = ResidentialBuilding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def residential_building_params
      params.require(:residential_building).permit(:dues, :latitude, :longitude)
    end
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/residential_buildings_helper.rb
module ResidentialBuildingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/residential_buildings/_form.html.erb
<%= form_for(@residential_building) do |f| %>
  <% if @residential_building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@residential_building.errors.count, "error") %> prohibited this residential_building from being saved:</h2>

      <ul>
      <% @residential_building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dues %><br>
    <%= f.text_field :dues %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/residential_buildings/edit.html.erb
<h1>Editing Residential Building</h1>

<%= render 'form' %>

<%= link_to 'Show', @residential_building %> |
<%= link_to 'Back', residential_buildings_path %>

app/views/residential_buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Residential Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Dues</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @residential_buildings.each do |residential_building| %>
      <tr>
        <td><%= residential_building.dues %></td>
        <td><%= residential_building.latitude %></td>
        <td><%= residential_building.longitude %></td>
        <td><%= link_to 'Show', residential_building %></td>
        <td><%= link_to 'Edit', edit_residential_building_path(residential_building) %></td>
        <td><%= link_to 'Destroy', residential_building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Residential building', new_residential_building_path %>

app/views/residential_buildings/new.html.erb
<h1>New Residential Building</h1>

<%= render 'form' %>

<%= link_to 'Back', residential_buildings_path %>

app/views/residential_buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dues:</strong>
  <%= @residential_building.dues %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @residential_building.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @residential_building.longitude %>
</p>

<%= link_to 'Edit', edit_residential_building_path(@residential_building) %> |
<%= link_to 'Back', residential_buildings_path %>