config/routes.rb
Rails.application.routes.draw do
  devise_for :residents, controllers: {
                       registrations: 'residents/registrations',
                       :omniauth_callbacks => "residents/omniauth_callbacks"
                   }
  root 'residents#index'

  get '/logout' => 'application#logout'
  resources :families
  resources :complaints
  resources :communities
  resources :people
  resources :neighbourhoods
  resources :polls

  get 'residents/me' => 'residents#me'
  resources :residents do
    get :approve, :on => :collection
  end
  resources :attempts
  resources :surveys
  resources :apartments
  resources :flats
  resources :workers
  resources :tags
  resources :residential_buildings
  resources :living_spaces
  resources :information

  resources :posts do
    resources :comments
  end

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :neighbourhood
  has_many :flats
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :information
  belongs_to :resident
end

app/models/community.rb
class Community < ActiveRecord::Base
  has_and_belongs_to_many :residents
  has_and_belongs_to_many :workers

  has_many :members
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  belongs_to :resident
end

app/models/family.rb
class Family < ActiveRecord::Base
  has_many :residents
  belongs_to :living_space
end

app/models/flat.rb
class Flat < ActiveRecord::Base
  belongs_to :apartment
  has_many :residents
end

app/models/information.rb
class Information < ActiveRecord::Base
  has_many :tags
  has_many :comments
  belongs_to :resident
end

app/models/living_space.rb
class LivingSpace < ActiveRecord::Base
  has_one :family
  belongs_to :neighbourhood
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :resident
  belongs_to :community
end

app/models/neighbourhood.rb
class Neighbourhood < ActiveRecord::Base
  has_many :residents
  has_many :living_spaces
  has_many :apartments
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :resident
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :resident
  has_many :comments
  def score
    self.get_upvotes.size - self.get_downvotes.size
  end
end

__END__

How to implement a blog


There will be a blog controller.


index.html.erb
--------------
Will show a list of all the posts


tag

app/models/resident.rb
class Resident < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :first_name, length: {minimum:2}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:facebook]
  belongs_to :family
  belongs_to :neighbourhood
  belongs_to :living_space
  has_many :posts
  has_and_belongs_to_many :communities
  has_many :comments
  has_many :polls
  has_many :informations
  has_many :members

  has_surveys

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |resident|
      resident.email = auth.info.email
      resident.password = Devise.friendly_token[0,20]
      resident.first_name = auth.info.name   # assuming the user model has a name
      resident.last_name = "."
      print "Image coming here"
      #user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  has_and_belongs_to_many :communities 
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:location, :longitude)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/apartments/_form.html.erb
<%= form_for(@apartment) do |f| %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% @apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.location %></td>
        <td><%= apartment.longitude %></td>
        <td><%= link_to 'Show', apartment %></td>
        <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apartment', new_apartment_path %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @apartment.location %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @apartment.longitude %>
</p>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>